[package]
name = "rustexamples"
version = "0.1.0"
authors = ["Adrián Romero <adrianromero@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
serde = { version ="1.0.105", features = ["derive"] }
serde_json = "1.0.48"
postgres = "0.17.2"